name: Master - Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      # If we have many bug we can test on all plateform
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.12
      CACHE_VERSION: v5

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: actions/checkout@v1

      - name: Install esy, rimraf, revery-packager
        run: npm install -g esy@0.6.6 rimraf@3.0.2 revery-packager@1.1.0

      - name: Install native dependencies on ubuntu-latest
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev mesa-utils mesa-utils-extra ragel libgtk-3-dev nasm tree libjpeg62 libsdl2-2.0.0

      - name: Install native dependencies on macos-latest
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install cmake libtool libpng ragel tree pkg-config || true
          brew upgrade cmake libtool libpng ragel tree pkg-config || true

      - name: Restore Cache
        id: restore-cache
        uses: despairblue/cache@462caf264919a479324c66ba453a5f80ac27f349
        with:
          path: |
            _export
            _tarballs
          key: ${{ runner.os }}-esy-${{ env.CACHE_VERSION }}-${{ hashFiles('esy.lock/index.json') }}
          restore-keys: |
            ${{ runner.os }}-esy-${{ env.CACHE_VERSION }}-
            ${{ runner.os }}-esy-

      - name: Install
        run: |
          esy install --cache-tarballs-path=./_tarballs

      - name: Import Build-Cache
        run: |
          esy import-dependencies _export
          rimraf _export

      - name: Build
        run: esy build

      - name: Export Build-Cache
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: |
          esy export-dependencies

      - name: Test
        run: esy test

      - name: Build Binary on ubuntu-latest
        if: matrix.os == 'ubuntu-latest'
        run: |
          revery-packager

      - name: Build Binary on macos-latest
        if: matrix.os == 'macos-latest'
        run: |
          env MACOSX_DEPLOYMENT_TARGET="10.12" revery-packager

      - name: Upload Binary on ubuntu-latest
        uses: actions/upload-artifact@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          name: linux-featuritis.AppImage
          path: _release/ReveryApp-x86_64.AppImage

      - name: Upload Binary on macos-latest
        uses: actions/upload-artifact@v1
        if: matrix.os == 'macos-latest'
        with:
          name: macosx-featuritis.dmg
          path: _release/ReveryApp.dmg
