name: Pull Request Windows

on: pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      # If we have many bug we can test on all plateform
      fail-fast: false
      matrix:
        os: [windows-2016]
    env:
      CACHE_VERSION: v5

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: actions/checkout@v1

      - name: Install esy, rimraf, revery-packager
        run: npm install -g esy@0.6.4 rimraf@3.0.2 revery-packager@1.1.0

      - name: Install native dependencies
        if: false
        run: npm install -g windows-build-tools

      - name: Install
        run: esy install

      - name: Print esy cache directory
        id: print_esy_cache
        run: node .github/workflows/print_esy_cache.js

      - name: Create Random Number
        id: random
        run: echo "::set-output name=number::$(node -e 'console.log(Math.random())')"

      - name: Restore Cache
        id: restore-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.print_esy_cache.outputs.esy_cache }}
          # Don't use the same prefix for `key` to make sure that  we're not
          # creating one that would be matching the `restore-keys`.
          # Also we use the sha and a random number to make sure that we can
          # rerun the workflow without using the empty cache we just create.
          key: pr-${{ runner.os }}-esy-${{ github.sha }}-${{ steps.random.outputs.number }}
          restore-keys: |
            ${{ runner.os }}-esy-${{ env.CACHE_VERSION }}
            ${{ runner.os }}-esy-

      - name: Build
        run: esy build

      - name: Test
        run: esy test

      - name: Build Binary
        if: false
        run: |
          ls D:\a\featuritis\featuritis\_esy\default\store\i\hello_reason-a307a664\ || true
          ls D:\a\featuritis\featuritis\_esy\default\store\i\hello_reason-a307a664\bin || true
          revery-packager || true
          ls _release/ || true

      # Delete build cache so it cannot be saved. Every OS only has one
      # cache that is created every Monday by the prime-cache workflow.
      # Otherwise the caches would start evicting each other since they add
      # up to roughly 4 GB for all OSes together.
      - name: Delete Cache
        if: always()
        run: rimraf ${{ steps.print_esy_cache.outputs.esy_cache }}
